OPENAI_API_KEY = "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"
SMTP_EMAIL = "kmaimidi@gmail.com"
SMTP_PASSWORD = "wautngyzmqokupjt"
ADMIN_PASSWORD = "admin123"
RECEPTIONIST_PASSWORD = "reception123"

